apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: op-hello-world-secret-reader
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: op-hello-world-secret-reader
subjects:
- kind: ServiceAccount
  name: op-hello-world-controller-manager
  namespace: op-hello-world-system