apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: observability
data:
  config.alloy: |
    ////////////////////////////////////////////////////////////////////////////
    // Alloy Log Settings
    logging {
      level = "info"
      format = "json"
    }
    
    ///////////////////////////////////////////////////////////////////////////
    // Kubernetes Discovery and Relabeling
    
    discovery.kubernetes "pod" {
        role = "pod"
    }
    
    discovery.relabel "pod" {
      targets = discovery.kubernetes.pod.targets

      rule {
        source_labels = ["__meta_kubernetes_namespace"]
        action = "replace"
        target_label = "namespace"
      }

      rule {
        source_labels = ["__meta_kubernetes_pod_name"]
        action = "replace"
        target_label = "pod"
      }

      rule {
        source_labels = ["__meta_kubernetes_pod_container_name"]
        action = "replace"
        target_label = "container"
      }

      rule {
        source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
        action = "replace"
        target_label = "app"
      }

      rule {
        source_labels = ["__meta_kubernetes_namespace", "__meta_kubernetes_pod_container_name"]
        action = "replace"
        target_label = "job"
        separator = "/"
        replacement = "$1"
      }

      rule {
        source_labels = ["__meta_kubernetes_pod_uid", "__meta_kubernetes_pod_container_name"]
        action = "replace"
        target_label = "__path__"
        separator = "/"
        replacement = "/var/log/pods/*$1/*.log"
      }

      rule {
        source_labels = ["__meta_kubernetes_pod_container_id"]
        action = "replace"
        target_label = "container_runtime"
        regex = "^(\\S+):\\/\\/.+$"
        replacement = "$1"
      }
    }
    
    ///////////////////////////////////////////////////////////////////////////
    // Loki
    
    loki.write "default" {
      endpoint {
        url = "http://lgtm.observability.svc.cluster.local:3100/loki/api/v1/push"
      }
    }
    
    
    loki.source.kubernetes "pod_logs" {
      targets    = discovery.relabel.pod.output
      forward_to = [loki.process.pod_logs.receiver]
    }

    loki.process "pod_logs" {
      stage.static_labels {
          values = {
            cluster = "LOCAL",
          }
      }

      forward_to = [loki.write.default.receiver]
    }
    
    local.file_match "node_logs" {
      path_targets = [{
          // Monitor syslog to scrape node-logs
          __path__  = "/var/log/syslog",
          job       = "node/syslog",
          node_name = sys.env("HOSTNAME"),
          cluster   = "LOCAL",
      }]
    }

    loki.source.file "node_logs" {
      targets    = local.file_match.node_logs.targets
      forward_to = [loki.write.default.receiver]
    }
    
    loki.source.kubernetes_events "cluster_events" {
      job_name   = "integrations/kubernetes/eventhandler"
      log_format = "logfmt"
      forward_to = [
        loki.process.cluster_events.receiver,
      ]
    }

    loki.process "cluster_events" {
      forward_to = [loki.write.default.receiver]

      stage.static_labels {
        values = {
          cluster = "LOCAL",
        }
      }

      stage.labels {
        values = {
          kubernetes_cluster_events = "job",
        }
      }
    }
    
    ///////////////////////////////////////////////////////////////////////////
    // Mimir (Prometheus)
    
    prometheus.remote_write "mimir" {
      endpoint {
        url = "http://mimir.observability:9009/api/v1/push"
      }
    }
    
    prometheus.scrape "default" {
      targets = discovery.relabel.pod.output

      forward_to = [prometheus.remote_write.mimir.receiver]

    }
    
