apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-config
  namespace: observability
data:
  mimir.yaml: |
    multitenancy_enabled: false
    
    server:
      http_listen_port: 9009
      grpc_listen_port: 9095
      log_level: info
    
    common:
      storage:
        backend: filesystem
        filesystem:
          dir: /tmp/mimir-data
    
    blocks_storage:
      storage_prefix: blocks
      tsdb:
        dir: /tmp/mimir-tsdb
      bucket_store:
        sync_dir: /tmp/mimir-tsdb-sync
    
    compactor:
      data_dir: /tmp/mimir-compactor
    
    distributor:
      ring:
        kvstore:
          store: inmemory
        instance_addr: 127.0.0.1
    
    ingester:
      ring:
        kvstore:
          store: inmemory
        instance_addr: 127.0.0.1
        replication_factor: 1
    
    ruler_storage:
      storage_prefix: rules
      
    alertmanager_storage:
      storage_prefix: alertmanager
    
    limits:
      max_global_series_per_user: 0
      max_global_series_per_metric: 0
      ingestion_rate: 1000000
      ingestion_burst_size: 2000000