apiVersion: v1
kind: Service
metadata:
  name: mimir
  namespace: default
spec:
  selector:
    app: mimir
  ports:
  - name: http
    port: 9009
    targetPort: 9009
  - name: grpc
    port: 9095
    targetPort: 9095
  type: ClusterIP