apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: op-hello-world-secret-reader
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  resourceNames:
  - ghcr-login
  verbs:
  - get