apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "lgtm.observability.svc.cluster.local:4317"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "grpc"
        - name: OTEL_EXPORTER_OTLP_INSECURE
          value: "true"
        - name: OTEL_SERVICE_NAME
          value: "op-hello-world-controller"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=op-hello-world-controller,service.namespace=op-hello-world-system"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: OTEL_METRICS_EXPORTER
          value: "otlp"
        - name: OTEL_LOGS_EXPORTER
          value: "otlp"