apiVersion: v1
kind: ConfigMap
metadata:
  name: pyroscope-config
  namespace: observability
data:
  pyroscope.yaml: |
    multitenancy_enabled: false
    
    server:
      http_listen_port: 4040
    
    storage:
      backend: filesystem
    
    ingester:
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
    
    distributor:
      ring:
        kvstore:
          store: inmemory