apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyroscope
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyroscope
  template:
    metadata:
      labels:
        app: pyroscope
    spec:
      containers:
      - name: pyroscope
        image: grafana/pyroscope:1.10.0
        args:
        - -config.file=/etc/pyroscope/pyroscope.yaml
        ports:
        - containerPort: 4040
          name: http
        volumeMounts:
        - name: pyroscope-config
          mountPath: /etc/pyroscope
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: pyroscope-config
        configMap:
          name: pyroscope-config