apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: default
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki:3100
      isDefault: false
      editable: true
    - name: Tempo
      type: tempo
      access: proxy
      url: http://tempo:3200
      isDefault: false
      editable: true
    - name: Mimir
      type: prometheus
      access: proxy
      url: http://mimir:9009/prometheus
      isDefault: true
      editable: true
    - name: Pyroscope
      type: grafana-pyroscope-datasource
      access: proxy
      url: http://pyroscope:4040
      isDefault: false
      editable: true