apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: observability
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      uid: loki
      access: proxy
      url: http://localhost:3100
      isDefault: false
      editable: true
    - name: Tempo
      type: tempo
      uid: tempo
      access: proxy
      url: http://localhost:3200
      isDefault: false
      editable: true
      jsonData:
        tracesToLogsV2:
          datasourceUid: loki
        tracesToMetrics:
          datasourceUid: prometheus
        serviceMap:
          datasourceUid: prometheus
        tracesToProfiles:
          datasourceUid: pyroscope
    - name: Prometheus (Internal)
      type: prometheus
      uid: prometheus
      access: proxy
      url: http://localhost:9090
      isDefault: false
      editable: true
      jsonData:
        exemplarTraceIdDestinations:
          - name: trace_id
            datasourceUid: tempo
    - name: Pyroscope
      type: grafana-pyroscope-datasource
      uid: pyroscope
      access: proxy
      url: http://pyroscope.observability:4040
      isDefault: false
      editable: true