apiVersion: v1
kind: Namespace
metadata:
  name: observability
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lgtm-pvc
  namespace: observability
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lgtm
  namespace: observability
  labels:
    app: lgtm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lgtm
  template:
    metadata:
      labels:
        app: lgtm
    spec:
      containers:
      - name: lgtm
        image: grafana/otel-lgtm:0.11.6
        ports:
        - containerPort: 3000
          name: grafana
        - containerPort: 3100
          name: loki
        - containerPort: 9090
          name: prometheus
        - containerPort: 3200
          name: tempo
        - containerPort: 4317
          name: otlp-grpc
        - containerPort: 4318
          name: otlp-http
        env:
        - name: GF_SECURITY_ADMIN_USER
          value: "admin"
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin"
        - name: GF_FEATURE_TOGGLES_ENABLE
          value: "traceQLEditor traceToProfiles profilesExplorer"
        - name: GF_INSTALL_PLUGINS
          value: "grafana-pyroscope-datasource"
        - name: GF_PATHS_PROVISIONING
          value: "/etc/grafana/provisioning"
        volumeMounts:
        - name: storage
          mountPath: /var/lib/grafana
        - name: datasources
          mountPath: /etc/grafana/provisioning/datasources
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: lgtm-pvc
      - name: datasources
        configMap:
          name: grafana-datasources
---
apiVersion: v1
kind: Service
metadata:
  name: lgtm
  namespace: observability
  labels:
    app: lgtm
spec:
  selector:
    app: lgtm
  ports:
  - name: grafana
    port: 3000
    targetPort: 3000
  - name: loki
    port: 3100
    targetPort: 3100
  - name: prometheus
    port: 9090
    targetPort: 9090
  - name: tempo
    port: 3200
    targetPort: 3200
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
  - name: otlp-http
    port: 4318
    targetPort: 4318
  type: ClusterIP