# Certificate for metrics server TLS
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: metrics-certs
  namespace: system
spec:
  secretName: metrics-server-cert
  dnsNames:
  - SERVICE_NAME.SERVICE_NAMESPACE.svc
  - SERVICE_NAME.SERVICE_NAMESPACE.svc.cluster.local
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned-issuer