# Self-signed ClusterIssuer for development/testing
# In production, replace with proper CA or ACME issuer
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}